import { EARTH_RADIUS_KM } from "../physics/constants";
import { degToRad, radToDeg } from "../physics/orbits/angles";
import {
  eccentricAnomalyToTrueAnomaly,
  solveKeplerEquation,
} from "../physics/orbits/conversions";
import type {
  ExplorerHistoricalCatalogObject,
  ExplorerHistoricalOrbitState,
} from "./explorerHistoricalCatalog";

export const HISTORICAL_RECONSTRUCTION_METHOD =
  "orbit-studio-gcat-reconstruction-v1" as const;
const reconstructionCache = new WeakMap<
  ExplorerHistoricalCatalogObject,
  Map<string, ExplorerHistoricalOrbitState | null>
>();

function validSummary(object: ExplorerHistoricalCatalogObject): boolean {
  const summary = object.orbitalSummary;
  if (!summary) return false;
  const {
    apogeeAltitudeKm,
    argumentOfPeriapsisDegReconstructed,
    inclinationDeg,
    meanAnomalyDegReconstructed,
    perigeeAltitudeKm,
    raanDegReconstructed,
    reconstructionVersion,
  } = summary;
  const lowerApsisAltitudeKm = Math.min(
    perigeeAltitudeKm,
    apogeeAltitudeKm,
  );
  const upperApsisAltitudeKm = Math.max(
    perigeeAltitudeKm,
    apogeeAltitudeKm,
  );
  const semiMajorAxisKm =
    (EARTH_RADIUS_KM + lowerApsisAltitudeKm +
      EARTH_RADIUS_KM + upperApsisAltitudeKm) / 2;
  return (
    Number.isFinite(perigeeAltitudeKm) &&
    Number.isFinite(apogeeAltitudeKm) &&
    Number.isFinite(inclinationDeg) &&
    Number.isFinite(raanDegReconstructed) &&
    Number.isFinite(argumentOfPeriapsisDegReconstructed) &&
    Number.isFinite(meanAnomalyDegReconstructed) &&
    reconstructionVersion === HISTORICAL_RECONSTRUCTION_METHOD &&
    lowerApsisAltitudeKm > -EARTH_RADIUS_KM &&
    semiMajorAxisKm > EARTH_RADIUS_KM &&
    inclinationDeg >= 0 &&
    inclinationDeg <= 180
  );
}

/**
 * Builds a stable educational orbit from source-reported orbital constraints.
 * The three angular elements unavailable in GCAT are generated by the canonical
 * package/export pipeline. Runtime code only converts the package's reconstructed
 * mean anomaly to the true anomaly required by the production two-body propagator.
 * The selected annual period end anchors the phase; no reconstructed value is
 * represented as a historical fix.
 */
export function reconstructHistoricalOrbitState(
  object: ExplorerHistoricalCatalogObject,
  selectedDateIso: string,
): ExplorerHistoricalOrbitState | undefined {
  const selectedDateMs = Date.parse(selectedDateIso);
  if (!Number.isFinite(selectedDateMs)) return undefined;
  const epoch = new Date(selectedDateMs).toISOString();
  let cachedByEpoch = reconstructionCache.get(object);
  if (!cachedByEpoch) {
    cachedByEpoch = new Map();
    reconstructionCache.set(object, cachedByEpoch);
  }
  const cached = cachedByEpoch.get(epoch);
  if (cached !== undefined) return cached ?? undefined;
  if (!validSummary(object)) {
    cachedByEpoch.set(epoch, null);
    return undefined;
  }
  const summary = object.orbitalSummary!;
  const perigeeRadiusKm = EARTH_RADIUS_KM +
    Math.min(summary.perigeeAltitudeKm, summary.apogeeAltitudeKm);
  const apogeeRadiusKm = EARTH_RADIUS_KM +
    Math.max(summary.perigeeAltitudeKm, summary.apogeeAltitudeKm);
  const semiMajorAxisKm = (perigeeRadiusKm + apogeeRadiusKm) / 2;
  const eccentricity = (apogeeRadiusKm - perigeeRadiusKm) /
    (apogeeRadiusKm + perigeeRadiusKm);
  if (!(semiMajorAxisKm > EARTH_RADIUS_KM) || eccentricity < 0 || eccentricity >= 1) {
    cachedByEpoch.set(epoch, null);
    return undefined;
  }

  const eccentricAnomaly = solveKeplerEquation(
    degToRad(summary.meanAnomalyDegReconstructed!),
    eccentricity,
  );
  const trueAnomalyDeg = radToDeg(
    eccentricAnomalyToTrueAnomaly(eccentricAnomaly, eccentricity),
  );
  const sourceRecordId = summary.recordId ?? object.id;

  const state: ExplorerHistoricalOrbitState = {
    id: `${object.id}:reconstructed:${HISTORICAL_RECONSTRUCTION_METHOD}`,
    objectId: object.id,
    catalogNumber: object.catalogNumber,
    epoch,
    sourceEpoch: summary.sourceEpoch,
    stateKind: "reconstructed",
    orbit: {
      altitudeKm: semiMajorAxisKm - EARTH_RADIUS_KM,
      eccentricity,
      inclinationDeg: summary.inclinationDeg,
      raanDeg: summary.raanDegReconstructed!,
      argumentOfPeriapsisDeg:
        summary.argumentOfPeriapsisDegReconstructed!,
      trueAnomalyDeg,
      epoch,
    },
    reconstruction: {
      method: HISTORICAL_RECONSTRUCTION_METHOD,
      deterministicSeed:
        `${HISTORICAL_RECONSTRUCTION_METHOD}:${sourceRecordId}`,
      constrainedFields: ["perigeeAltitudeKm", "apogeeAltitudeKm", "inclinationDeg"],
      synthesizedFields: ["raanDeg", "argumentOfPeriapsisDeg", "trueAnomalyDeg"],
      sourceEpoch: summary.sourceEpoch,
      regime: summary.regime,
    },
    sources: object.sources.filter((source) => source.sourceId === summary.sourceId),
  };
  cachedByEpoch.set(epoch, state);
  return state;
}
